**Declaring a matrix**

In [1]:
import numpy as np
A=np.array([
    [0,1.0,0],
    [0,0,1],
    [-6.0,-11.0,-6.0]])
A.view()

array([[  0.,   1.,   0.],
       [  0.,   0.,   1.],
       [ -6., -11.,  -6.]])

In [2]:
B=np.array([
    [2.0],
    [3.0],
    [1.0]
])
B.view()

array([[2.],
       [3.],
       [1.]])

In [3]:
C=np.array([
    [2.0,2.0,2.0],
    [-1.0,-1.0,0],
    [-2.0,-1.0,-1.0]
])
C.view()

array([[ 2.,  2.,  2.],
       [-1., -1.,  0.],
       [-2., -1., -1.]])

**Properties of matrices**

In [4]:
print("Shape of A =",A.shape)
print("Shape of B =",B.shape)
print("Determinant of A =",np.linalg.det(A))
print("Determinant of C =",np.linalg.det(C))
print("Trace of A =",np.trace(A))
print("Trace of C =",np.trace(C))
print("Rank of A =",np.linalg.matrix_rank(A))
print("Rank of B =",np.linalg.matrix_rank(B))
print("Transpose of C\n",C.T.view())

Shape of A = (3, 3)
Shape of B = (3, 1)
Determinant of A = -6.0
Determinant of C = -2.0
Trace of A = -6.0
Trace of C = 0.0
Rank of A = 3
Rank of B = 1
Transpose of C
 [[ 2. -1. -2.]
 [ 2. -1. -1.]
 [ 2.  0. -1.]]


**Matrix Multiplication**

In [5]:
P=np.matmul(A,C)
print("Product")
print(P.view())
print("Determinant of product =",np.linalg.det(P))

Product
[[-1. -1.  0.]
 [-2. -1. -1.]
 [11.  5. -6.]]
Determinant of product = 12.0


**Testing properties of matrices**

In [52]:
import numpy.linalg as l
A=np.array([[1.,2,4],[3,2,1],[4,5,6]])
print("A\n",A.view())
print("determinant of A:",l.det(A))
B=np.array([[1.,2,1],[1,1,1],[3,2,1]])
print("B\n",B.view())
print("determinant of B:",l.det(B))
print("detA-detB:",l.det(A)-l.det(B))
print("det(A-B):",l.det(A-B))
print("A-B\n",(A-B).view())
print("detAB: ",l.det(np.matmul(A,B)))
print("detBA:",l.det(np.matmul(B,A)))
print("TraceAB",np.trace(np.matmul(A,B)))
print("TraceBA:",np.trace(np.matmul(B,A)))
print("observation: the determinant calculations have more errors compared to the trace calculations")

A
 [[1. 2. 4.]
 [3. 2. 1.]
 [4. 5. 6.]]
determinant of A: 6.999999999999999
B
 [[1. 2. 1.]
 [1. 1. 1.]
 [3. 2. 1.]]
determinant of B: 2.0000000000000004
detA-detB: 4.999999999999998
det(A-B): 15.000000000000007
A-B
 [[0. 0. 3.]
 [2. 1. 0.]
 [1. 3. 5.]]
detAB:  14.000000000000078
detBA: 13.999999999999966
TraceAB 40.0
TraceBA: 40.0
observation: the determinant calculations have more errors compared to the trace calculations


**Inverse of Matrix**

In [8]:
Ainv=np.linalg.inv(A)
print(Ainv)
print("check A*Ainv=I")
print(np.matmul(A,Ainv))

[[ 1.          1.14285714 -0.85714286]
 [-2.         -1.42857143  1.57142857]
 [ 1.          0.42857143 -0.57142857]]
check A*Ainv=I
[[1.00000000e+00 2.22044605e-16 0.00000000e+00]
 [0.00000000e+00 1.00000000e+00 2.22044605e-16]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]


**Making an integer matrix whose inverse also contains integers** 

In [9]:
import numpy as np
import numpy.linalg as l
A=np.array([[1,2,4],[0,1,1],[0,0,-1]])
print("A\n",A.view())
print("determinant of A:",l.det(A))
print("performing column operations: Adding column 3 to columns 1 and 2")
for i in range(0,3):
    A[i,0]+=A[i,2]
    A[i,1]+=A[i,2]
print("A\n",A.view())
print("determinant of A:",l.det(A))
print("Inv_A\n",l.inv(A))

A
 [[ 1  2  4]
 [ 0  1  1]
 [ 0  0 -1]]
determinant of A: -1.0
performing column operations: Adding column 3 to columns 1 and 2
A
 [[ 5  6  4]
 [ 1  2  1]
 [-1 -1 -1]]
determinant of A: -0.9999999999999998
Inv_A
 [[ 1. -2.  2.]
 [ 0.  1.  1.]
 [-1.  1. -4.]]


**Creating triagonal matrices**

In [10]:
A1=np.diag([1.,2,1,2]) # main diagonal
A2=np.diag([1,3,1],-1)
A3=np.diag([2,1,2],1)
A=A1+A2+A3
print("A\n",A.view())

A
 [[1. 2. 0. 0.]
 [1. 2. 1. 0.]
 [0. 3. 1. 2.]
 [0. 0. 1. 2.]]


**Calculating roots of characteristic equation using symbolic toolbox** 

1/2


**Eigenvalues and eigenvectors**

In [11]:
[W,V]=np.linalg.eig(A)
print("Eigenvalues=",W)
print("Eigenvectors")
#V=np.round(V)
print(V.view())
# print("check")
# M=np.matmul(A,V)
# print(np.matmul(V.T,M))

Eigenvalues= [-1.07337936  0.56313359  4.07337936  2.43686641]
Eigenvectors
[[ 0.36860726  0.75667889 -0.32875614 -0.47384813]
 [-0.38213134 -0.1652838  -0.50519616 -0.34042823]
 [ 0.80582732 -0.51918815 -0.71870716  0.32512647]
 [-0.26219585  0.36133363 -0.34663563  0.74422399]]


**Solving LX=B using Forward substitution**

In [12]:
print("L")
L=np.array([
    [1.0,0,0],
    [2.0,3.0,0],
    [1.0,2.0,3.0]])
print(L)
print("B")
B=np.array([
    [2.0],
    [3.0],
    [1.0]
])
print(B)
print("Forward Substitution")
[r,c]=L.shape
for i in range(0,r):
    for j in range(0,i):
        B[i]=B[i]-(L[i,j]*B[j])
    B[i]=B[i]/L[i,i]

print(B)

L
[[1. 0. 0.]
 [2. 3. 0.]
 [1. 2. 3.]]
B
[[2.]
 [3.]
 [1.]]
Forward Substitution
[[ 2.        ]
 [-0.33333333]
 [-0.11111111]]


**Converting AX=B to UX=B' using Multipliers**
1. $M^{-1}$ inverse is not exaclty $-M$. The diagonal elements remain 1 whereas sign change occurs to the rest of the elements 

In [13]:
import numpy as np
print("AX=B")
print("A")
A=np.array([
    [2.0,1.0,1.0],
    [2.0,2.0,-1],
    [4.0,-1.0,6.0]
])
print(A)
print("B")
B=np.array([
    [9.0],
    [9.0],
    [16.0]
])
print(B)
print("Lower triangular matrix L")
L=np.array([
    [1.0,0,0],
    [1,1.0,0],
    [2.0,-3,1.0]
])
print("L")
print(L)
print("Now L inverse is the multiplier matrix")
print("M")
M=np.linalg.inv(L)
print(M)
print("check: MA should give us an upper triangular matrix")
U=np.matmul(M,A)
print("U")
print(U)
print("check: LU should give us back A matrix")
print("LU")
print(np.matmul(L,U))

AX=B
A
[[ 2.  1.  1.]
 [ 2.  2. -1.]
 [ 4. -1.  6.]]
B
[[ 9.]
 [ 9.]
 [16.]]
Lower triangular matrix L
L
[[ 1.  0.  0.]
 [ 1.  1.  0.]
 [ 2. -3.  1.]]
Now L inverse is the multiplier matrix
M
[[ 1.  0.  0.]
 [-1.  1.  0.]
 [-5.  3.  1.]]
check: MA should give us an upper triangular matrix
U
[[ 2.0000000e+00  1.0000000e+00  1.0000000e+00]
 [ 0.0000000e+00  1.0000000e+00 -2.0000000e+00]
 [ 0.0000000e+00  8.8817842e-16 -2.0000000e+00]]
check: LU should give us back A matrix
LU
[[ 2.  1.  1.]
 [ 2.  2. -1.]
 [ 4. -1.  6.]]


**LU Decomposition with pivoting**

In [14]:
import numpy as np
print("AX=B")
print("A")
A=np.array([
    [2.0,1.0,1.0],
    [2.0,1.0,-1],
    [4.0,-1.0,6.0]
])
print(A)
print("B")
B=np.array([
    [9.0],
    [9.0],
    [16.0]
])
print(B)
print("Pivoting matrix")
print("P")
P=np.array([[0,0,1],
            [0,1,0],
            [1,0,0]])
print(P)
print("PA")
A=np.matmul(P,A)
print(A)
print("PB")
B=np.matmul(P,B)
print("Lower triangular matrix L")
L=np.array([
    [1,0,0],
    [0.5,1.0,0],
    [0.5,1,1.0]
])
print("L")
print(L)
print("Now L inverse is the multiplier matrix")
print("M")
M=np.linalg.inv(L)
print(M)
print("check: MA should give us an upper triangular matrix")
U=np.matmul(M,A)
print("U")
print(U)
print("check: LU should give us back A matrix")
print("LU")
print(np.matmul(L,U))

AX=B
A
[[ 2.  1.  1.]
 [ 2.  1. -1.]
 [ 4. -1.  6.]]
B
[[ 9.]
 [ 9.]
 [16.]]
Pivoting matrix
P
[[0 0 1]
 [0 1 0]
 [1 0 0]]
PA
[[ 4. -1.  6.]
 [ 2.  1. -1.]
 [ 2.  1.  1.]]
PB
Lower triangular matrix L
L
[[1.  0.  0. ]
 [0.5 1.  0. ]
 [0.5 1.  1. ]]
Now L inverse is the multiplier matrix
M
[[ 1.   0.   0. ]
 [-0.5  1.   0. ]
 [ 0.  -1.   1. ]]
check: MA should give us an upper triangular matrix
U
[[ 4.  -1.   6. ]
 [ 0.   1.5 -4. ]
 [ 0.   0.   2. ]]
check: LU should give us back A matrix
LU
[[ 4. -1.  6.]
 [ 2.  1. -1.]
 [ 2.  1.  1.]]


**LDV decomposition**

In [15]:
import numpy as np
print("AX=B")
print("A")
A=np.array([
    [2.0,1.0,1.0],
    [2.0,2.0,-1],
    [4.0,-1.0,6.0]
])
print(A)
print("B")
B=np.array([
    [9.0],
    [9.0],
    [16.0]
])
print(B)
print("Lower triangular matrix L")
L=np.array([
    [1.0,0,0],
    [1,1.0,0],
    [2.0,-3,1.0]
])
print("L")
print(L)
print("Now L inverse is the multiplier matrix")
print("M")
M=np.linalg.inv(L)
print(M)
print("check: MA should give us an upper triangular matrix")
U=np.matmul(M,A)
print("U")
print(U)
print("check: LU should give us back A matrix")
print("LU")
print(np.matmul(L,U))
print("U=DV")
print("U")
U=np.array([
    [2.0,1.0,1.0],
    [0,1.0,-2],
    [0,0,-2.0]
])
print(U)
print("L")
print(L)
print("D") # D is obtained by taking the diagnol element common in the U matrix
D=np.array([[2.0,0,0],
            [0,1.0,0],
            [0,0,-2.0]])
print(D)
print("V")
V=np.array([[1,0.5,0.5],
            [0,1,-2],
            [0,0,1]])
print(V)
print("check:DV must give U")
print("DV")
print(np.matmul(D,V))

AX=B
A
[[ 2.  1.  1.]
 [ 2.  2. -1.]
 [ 4. -1.  6.]]
B
[[ 9.]
 [ 9.]
 [16.]]
Lower triangular matrix L
L
[[ 1.  0.  0.]
 [ 1.  1.  0.]
 [ 2. -3.  1.]]
Now L inverse is the multiplier matrix
M
[[ 1.  0.  0.]
 [-1.  1.  0.]
 [-5.  3.  1.]]
check: MA should give us an upper triangular matrix
U
[[ 2.0000000e+00  1.0000000e+00  1.0000000e+00]
 [ 0.0000000e+00  1.0000000e+00 -2.0000000e+00]
 [ 0.0000000e+00  8.8817842e-16 -2.0000000e+00]]
check: LU should give us back A matrix
LU
[[ 2.  1.  1.]
 [ 2.  2. -1.]
 [ 4. -1.  6.]]
U=DV
U
[[ 2.  1.  1.]
 [ 0.  1. -2.]
 [ 0.  0. -2.]]
L
[[ 1.  0.  0.]
 [ 1.  1.  0.]
 [ 2. -3.  1.]]
D
[[ 2.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -2.]]
V
[[ 1.   0.5  0.5]
 [ 0.   1.  -2. ]
 [ 0.   0.   1. ]]
check:DV must give U
DV
[[ 2.  1.  1.]
 [ 0.  1. -2.]
 [ 0.  0. -2.]]


**Cholesky decomposition**

In [16]:
import numpy as np
A=np.array([[4.0,-2.0,4.0,2.0],
            [-2,10,-2,-7],
            [4,-2,8,4],
            [2,-7,4,7]])
print("A")
print(A)
print("cholesky factor R")
R=np.array([[2.0,-1,2,1],
            [0,3,0,-2],
            [0,0,2,1],
            [0,0,0,1.0]])
print(R)
print("check: R transpose R must give us A")
print(np.matmul(R.T,R))

A
[[ 4. -2.  4.  2.]
 [-2. 10. -2. -7.]
 [ 4. -2.  8.  4.]
 [ 2. -7.  4.  7.]]
cholesky factor R
[[ 2. -1.  2.  1.]
 [ 0.  3.  0. -2.]
 [ 0.  0.  2.  1.]
 [ 0.  0.  0.  1.]]
check: R transpose R must give us A
[[ 4. -2.  4.  2.]
 [-2. 10. -2. -7.]
 [ 4. -2.  8.  4.]
 [ 2. -7.  4.  7.]]


**Vector norms**

In [17]:
A=np.array([
    [1],[2],[1]
])
print("A")
print(A)

acc=0
for i in A:
    acc = acc + abs(i)
print("One norm or Taxi-norm of A:",acc)

acc=0
for i in A:
    acc=acc+pow(i,2)
acc=np.sqrt(acc)
print("Two norm of A:",acc)

acc=abs(A[0])
for i in A:
    if(acc<abs(i)):
        acc=abs(i)
print("Infinity norm of A:",acc)

print("Infact these norms are same for [1 2 1]* or [1 -2 1]*")

A
[[1]
 [2]
 [1]]
One norm or Taxi-norm of A: [4]
Two norm of A: [2.44948974]
Infinity norm of A: [2]
Infact these norms are same for [1 2 1]* or [1 -2 1]*


**Induced norms or Matrix norms**

In [18]:
A=np.array([
    [1,2,3],
    [3,2,1],
    [4,1,2]
])

 print("One norm of A:")

IndentationError: unexpected indent (<ipython-input-18-745ffbe1b264>, line 7)